version: '3.4'

services:
  cntact:
    image: ${DOCKER_REGISTRY-}cntact
    build:
      context: .
      dockerfile: Cntact/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__Database=Host=db;Port=5432;Database=my_contacts;User Id=postgres;Password=123

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: my_contacts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: